### ISSUE TITLE
Dockerfile no longer valid (emdebian dead, jessie migration)

### ISSUE THREAD

**Issue by taziden** [bleuchtang/sunxi-debian#20]
Due to the end of emdebian.org and Jessie release, Dockerfile needs to be updated. As of today, it's no longer working.

**Comment by bleuchtang** [comment]
Indeed, we should use CrossToolchains (https://wiki.debian.org/CrossToolchains) instead.

**Comment by taziden** [comment]
Here is a PR for this : https://github.com/bleuchtang/sunxi-debian/pull/22

**Comment by sbadia** [comment]
Fixed by #23 thanks @taziden !
